spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: journal
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: xxxxxxxxxxxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    key: cde443e93cd45ef36c9cc8fb3fdcb833